export const SET_TESTS_TYPE = 'SET_TESTS_TYPE';
export const UPDATE_URL = 'UPDATE_URL';
export const SET_SCREEN_VIEW_MODE = 'SET_SCREEN_VIEW_MODE';
export const SET_TESTS_VIEW_MODE = 'SET_TESTS_VIEW_MODE';
