export const SET_TESTS_TYPE = 'SET_TESTS_TYPE';

export const INIT_GUI = 'INIT_GUI';
export const RUN_ALL = 'RUN_ALL';
export const RUN_FAILED = 'RUN_FAILED';
export const ACCEPT_ALL_REFS = 'ACCEPT_ALL_REFS';
export const UPDATE_URL = 'UPDATE_URL';
export const SET_SCREEN_VIEW_MODE = 'SET_SCREEN_VIEW_MODE';
export const SET_TESTS_VIEW_MODE = 'SET_TESTS_VIEW_MODE';

export const SET_IS_OPEN_FOR_TEST_BOX = 'SET_IS_OPEN_FOR_TEST_BOX';
export const SET_IS_OPEN_FOR_BROWSER = 'SET_IS_OPEN_FOR_BROWSER';
export const SET_IS_OPEN_FOR_VIEW = 'SET_IS_OPEN_FOR_VIEW';
export const SET_SCREEN_FOR_VIEW = 'SET_SCREEN_FOR_VIEW';
